services:
  - type: web
    name: sf-config-compare
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: LOG_LEVEL
        value: INFO
